### ISSUE TITLE
cc26xx-ble-client-demo

### ISSUE THREAD

**Issue by cursedcelestial** [spoerk/contiki#2]
not working cant make a bin file to burn on the device same with the server example.

**Comment by spoerk** [comment]
Can you tell me what the error message during compilation is?

**Comment by cursedcelestial** [comment]
Thanks for the response. The compilation error is solved but i have have been stuck on the same example cc26xx-ble-client-demo & cc26xx-ble-server-demo.


To elaborate on the issue it is directed in the readme to add the server ip in client.c which i am doing by converting the ble mac to ipv6 but the server is not responding to client icmp ping, client is stuck in echo loop and the communication is not proceeding.


Do I have to assign IP to server or there is a way around?



Best Regards

________________________________

**Comment by Li-Weihang** [comment]
@cursedcelestial Have you defined the BLE_MODE_CONF_INIT_PEER_ADDR in line 62 of project-conf.h in ../cc26xx-ble-server-demo/ ? You may set this value to MAC address of client.

**Comment by spoerk** [comment]
Sorry for my delayed reply.

@cursedcelestial : Does the problem still persist?

**Comment by sheetalsingala** [comment]
Can I use a CC2650 as one node and raspberry pi as the other ?

**Comment by spoerk** [comment]
Yes, you can use one or multiple TI CC2650 devices as IPv6-over-BLE node devices and a Raspberry Pi as a border router.

The README of the cc26xx-ble-client-demo provides a short guide on how to setup the TI CC2650 as node device. The [NordicSemiconductor guide](http://developer.nordicsemi.com/nRF5_IoT_SDK/doc/0.9.0/html/a00092.html) on how to setup the Pi should help you too.

**Comment by sheetalsingala** [comment]
The bin file does not get created because of the following errors--

contiki-srf06-cc26xx.a(contiki-main.o): In function `main':
contiki-main.c:(.text.startup.main+0x210): undefined reference to `ble_null_par_driver'
contiki-main.c:(.text.startup.main+0x218): undefined reference to `ble_l2cap_driver'
contiki-srf06-cc26xx.a(netstack.o): In function `netstack_init':
netstack.c:(.text.netstack_init+0x28): undefined reference to `ble_null_par_driver'
netstack.c:(.text.netstack_init+0x30): undefined reference to `ble_l2cap_driver'
contiki-srf06-cc26xx.a(nullsec.o): In function `send':
nullsec.c:(.text.send+0x1c): undefined reference to `ble_l2cap_driver'
contiki-srf06-cc26xx.a(rf-core.o): In function `process_thread_rf_core_process':
rf-core.c:(.text.process_thread_rf_core_process+0x58): undefined reference to `ble_null_par_driver'

What is the mistake?

**Comment by CKR1** [comment]
I am too not being able to make bin file . Every time i try to make it shows this ->>>


make TARGET=srf06-cc26xx BOARD=sensortag/cc2650 server.bin CPU_FAMILY=cc26xx
fatal: Not a git repository: '../../../.git'
make: *** No rule to make target 'server.bin'.  Stop.
utpal@utpal-Lenovo-ideapad-320-15IKB:~/Desktop/contiki-master/examples/cc26xx/cc26xx-ble-server-demo$ 

Please Help me out with this, reply asap please

**Comment by spoerk** [comment]
As the log-output in your comment states, the make target server.bin does not exist.
You need to compile the example using: `make TARGET=srf06-cc26xx BOARD=sensortag/cc2650 all`.

**Comment by CKR1** [comment]
Thank you so much sir for replying , but even this didn't work 
Now it shows this as output 
make TARGET=srf06-cc26xx BOARD=sensortag/cc2650 all
fatal: Not a git repository: '../../../.git'
  CC        server.c
In file included from ../../../platform/srf06-cc26xx/./contiki-conf.h:447:0,
                 from ../../../core/./contiki.h:38,
                 from server.c:39:
../../../platform/srf06-cc26xx/sensortag/cc2650/board.h:58:10: fatal error: ioc.h: No such file or directory
 #include "ioc.h"
          ^~~~~~~
compilation terminated.
../../../Makefile.include:253: recipe for target 'server.o' failed
make: *** [server.o] Error 1

**Comment by spoerk** [comment]
It looks like you may be in a wrong folder to compile.
How did you download the source code (just download or cloned it with github) and in what folder do you execute the compilation?

**Comment by dkopatz** [comment]
I had the same error. One needs to clone the git repository with "git clone --recursive". After this the error was fixed for me.

**Comment by CKR1** [comment]
Thank you so much!! I will look into it once more.
